### ISSUE TITLE
Control enforces a Buffer for value which fails with writeString()

### ISSUE THREAD

**Issue by soulchild** [ldapjs/node-ldapjs#593]
The current implementation [asserts](https://github.com/ldapjs/node-ldapjs/blob/master/lib/controls/control.js#L24) that the `value` parameter passed to the Control constructor is of type `Buffer`. This value is then [passed](https://github.com/ldapjs/node-ldapjs/blob/master/lib/controls/control.js#L54) to `ber` via the `writeString()` method which fails because `value` is a `Buffer` not a `String`:

> TypeError: argument must be a string (was: object)

IMHO, this basically makes creating a custom control without implementing a custom `_toBer()` method impossible.

Would it make sense to replace `writeString()` with `writeBuffer()` to get this working or am I just misunderstanding things?

**Comment by soulchild** [comment]
Seems like `writeBuffer()` expects a `BerWriter` buffer, so the proposed change won't fix my issue.

I'm trying to implement a Proxy Authentication Control which basically needs to send the corresponding control type OID (2.16.840.1.113730.3.4.18), criticality set to true and the proxy user as the value. 

Is it even possible to just use the provided Control class for this or do I have to subclass it like the other (more complex) control types do? An example would be helpful. ;-)

**Comment by jsumners** [comment]
Please look at the `next` branch to determine if this issue is already resolved.

**Comment by soulchild** [comment]
Unfortunately, the `next` branch doesn't solve the problem. Is there a simple solution which does not involve reading through the LDAP wire protocol? 😄AFAICT, I'll just need to send a simple value (string) together with the OID and criticality. Thanks!

**Comment by jsumners** [comment]
PRs are welcome.

**Comment by soulchild** [comment]
I went ahead and created a Control subclass for my Proxy Authentication Control by copying one of the controls which are shipping with the library. At first it didn't work ("authzId mapping failed"). After spending some time inspecting what went over the wire with tcpdump I figured out that the `_toBer()` methods in the example controls all instantiated a new `BerWriter` instance to write the value(s). This trips up the protocol sequence. The fix was simple:

```js
ProxyAuthControl.prototype._toBer = function _toBer(ber) {
  if (!this._value) {
    return;
  }
  ber.writeString(this._value);
};
```

If you're interested, I could create a PR to have the ProxyAuthControl included in the library?

**Comment by jsumners** [comment]
It's possible I have it fixed in https://github.com/ldapjs/controls . I distinctly remember fixing something with the `BerWriter` not allowing empty values, but I cannot find where at the moment.

But as I said, PRs to resolve any issues are welcome. As I outline in #570, my time for this project is very limited and progress will be made much quicker with help.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
